<?php

namespace NosBundles\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * Retourne la liste des produits correspondant à la catégorie passée en paramètre (Name)
     * Si aucune catégorie n'est spécifiée, la liste de tout les produits est renvoyée.
     * @param int $NameCategorie nom de la categorie à rechercher
     * @return NosBundles\ProductBundle\Entity\Product[] Liste des produits de la catégorie demandée
     */
    public function findByCategorie($NameCategorie = "")
    {
        /* Création de la requète avec le query builder */
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select("p")
                     ->from("NosBundlesProductBundle:Product", "p");

        /* Si on reçoit un nom de catégorie valide alors on recherche les Films de cette catégorie uniquement */
        if ($NameCategorie != "") {
            $queryBuilder->where("p.prod_cat like '% :NameCategorie %'")->setParameter("NameCategorie", $NameCategorie);
        }
        /* Puis on retourne la liste des films du genre demandé */
        return $queryBuilder->getQuery()->getResult();
    }
}
