nos_bundles_user:
    resource: "@NosBundlesUserBundle/Controller/"
    type:     annotation
    prefix:   /

nos_bundles_product:
    resource: "@NosBundlesProductBundle/Controller/"
    type:     annotation
    prefix:   /

<<<<<<< HEAD
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
=======
_user_bundle:
    resource: "@NosBundlesUserBundle/Resources/config/routing.yml"
>>>>>>> 6b77fbef3eb4ddf8a1814b52fdcd699992e5b309
