nos_bundles_user:
    resource: "@NosBundlesUserBundle/Controller/"
    type:     annotation
    prefix:   /

nos_bundles_product:
    resource: "@NosBundlesProductBundle/Controller/"
    type:     annotation
    prefix:   /

_user_bundle:
    resource: "@NosBundlesUserBundle/Resources/config/routing.yml"
